const BUILDING_TYPE = {
  BUILDING: 'BUILDING',
  RESIDENTIAL: 'RESIDENTIAL',
  COMMERCIAL: 'COMMERCIAL',
  INDUSTRIAL: 'INDUSTRIAL',
  ROAD: 'ROAD',
  POWER_PLANT: 'POWER_PLANT',
  POWER_LINE: 'POWER_LINE',
} as const;

const ROAD_TYPE = {
  END: 'END',
  STRAIGHT: 'STRAIGHT',
  CORNER: 'CORNER',
  THREE_WAY: 'THREE-WAY',
  FOUR_WAY: 'FOUR-WAY',
} as const;

type BuildingType = (typeof BUILDING_TYPE)[keyof typeof BUILDING_TYPE];

export { BUILDING_TYPE, ROAD_TYPE, BuildingType };

